[package]
name = "spacemap"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-only"

[dependencies]
arboard = { version = "3.6", default-features = false, features = ["wayland-data-control"] }
chrono = "0.4.45"
eframe = "0.36.2"
egui = "0.36.2"
egui_extras = { version = "0.36.2", default-features = false }
infer = "0.22.0"
libc = "0.2.189"
rayon = "1.12.0"
rfd = "0.17.2"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
stacker = "0.1.25"
trash = "5.2.6"
unicode-normalization = "0.1.25"
uzers = "0.12.2"
